" plug.vim plugins
call plug#begin('~/.vim/plugged')
  Plug 'fatih/vim-go'
" Add plugins to &runtimepath
call plug#end()

highlight ColorColumn ctermbg=red

syntax on
set background=dark

set hlsearch
set incsearch

set tabstop=2
set expandtab
set shiftwidth=2
set number
set mouse=a
set ttymouse=xterm2
set smartindent
set autoindent
filetype indent on
