" plug.vim plugins
call plug#begin('~/.vim/plugged')
  Plug 'fatih/vim-go'
" Add plugins to &runtimepath
call plug#end()



set colorcolumn=80
highlight ColorColumn ctermbg=red

syntax on
set background=dark

set hlsearch
set incsearch

set tabstop=2
set expandtab
set shiftwidth=2
set number
set mouse=a
set ttymouse=xterm2
set smartindent
set autoindent
filetype indent on


" Load vim-plug
if empty(glob("~/.vim/autoload/plug.vim"))
      execute '!curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif
